import { StyleSheet } from "react-native";
import { AppColors, FontFamily, FontSize, Spacing, MaxContentWidth } from "@/constants/theme";

const C = AppColors;

export const cartStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.lightBg,
  },
  centered: {
    justifyContent: "center",
    alignItems: "center",
  },
  safeArea: {
    flex: 1,
    maxWidth: MaxContentWidth,
    width: "100%",
    alignSelf: "center",
  },
  header: {
    paddingHorizontal: Spacing.four,
    paddingVertical: Spacing.three,
    alignItems: "flex-end",
  },
  headerTitle: {
    fontSize: FontSize.h3,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  headerSubtitle: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.medium,
    color: C.textMuted,
    marginTop: 4,
    textAlign: "right",
  },
  scrollContent: {
    paddingBottom: 110,
  },
  listContainer: {
    gap: Spacing.two,
    paddingHorizontal: Spacing.four,
  },
  // ─── Cart Item Card ────────────────────────────────────────────────────────
  cartItemCard: {
    flexDirection: "row-reverse",
    borderRadius: 18,
    overflow: "hidden",
    padding: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.white,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
    position: "relative",
  },
  cartItemImage: {
    width: 105,
    height: 105,
    borderRadius: 14,
  },
  cartItemDetails: {
    flex: 1,
    marginRight: Spacing.three,
    alignItems: "flex-end",
    gap: 2,
  },
  cartItemName: {
    fontSize: FontSize.lg,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  cartItemCat: {
    fontSize: FontSize.xs,
    color: C.textMuted,
  },
  cartItemPrice: {
    color: C.primary,
    fontSize: FontSize.base,
    fontFamily: FontFamily.bold,
  },
  itemQuantityContainer: {
    flexDirection: "row-reverse",
    alignItems: "center",
    backgroundColor: C.bgElement,
    borderRadius: 14,
    paddingHorizontal: 4,
    paddingVertical: 2,
    gap: 6,
  },
  actionBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.white,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  quantityText: {
    fontSize: FontSize.base,
    fontFamily: FontFamily.bold,
    color: C.textDark,
    marginHorizontal: 4,
  },
  deleteBtn: {
    position: "absolute",
    top: 10,
    left: 10,
    padding: 8,
  },
  // ─── Summary card ─────────────────────────────────────────────────────────
  summaryCard: {
    marginHorizontal: Spacing.four,
    marginTop: Spacing.four,
    borderRadius: 16,
    padding: Spacing.three + 2,
    gap: Spacing.two,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.white,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  summaryTitle: {
    textAlign: "right",
    fontSize: FontSize.lg,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  summaryRow: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
  },
  summaryLabel: {
    fontSize: FontSize.md,
    color: C.textMuted,
  },
  summaryValue: {
    fontSize: FontSize.md,
    fontFamily: FontFamily.semiBold,
    color: C.textDark,
  },
  freeDelivery: {
    fontSize: FontSize.md,
    fontFamily: FontFamily.bold,
    color: C.success,
  },
  divider: {
    height: 1,
    backgroundColor: C.border,
    marginVertical: Spacing.one,
  },
  totalLabel: {
    fontSize: FontSize.lg,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  totalValue: {
    fontSize: FontSize.xl,
    fontFamily: FontFamily.bold,
    color: C.primary,
  },
  checkoutBtn: {
    backgroundColor: C.primary,
    paddingVertical: Spacing.three,
    borderRadius: 12,
    alignItems: "center",
    marginTop: Spacing.two,
  },
  checkoutBtnText: {
    color: C.white,
    fontSize: FontSize.md,
    fontFamily: FontFamily.bold,
  },
  // ─── Empty state ──────────────────────────────────────────────────────────
  emptyTitle: {
    fontSize: FontSize.xxl,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  emptySubtitle: {
    textAlign: "center",
    marginBottom: Spacing.four,
    color: C.textMuted,
  },
  shopBtn: {
    backgroundColor: C.primary,
    paddingHorizontal: Spacing.four,
    paddingVertical: Spacing.two,
    borderRadius: 12,
  },
  shopBtnText: {
    color: C.white,
    fontFamily: FontFamily.bold,
  },
  // ─── Checkout view ────────────────────────────────────────────────────────
  checkoutContainer: {
    marginHorizontal: Spacing.four,
    borderRadius: 16,
    padding: Spacing.three + 2,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.white,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  checkoutHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.three,
  },
  backBtn: {
    paddingVertical: Spacing.one,
  },
  backBtnText: {
    color: C.primary,
    fontSize: FontSize.sm,
    fontFamily: FontFamily.bold,
  },
  checkoutTitle: {
    fontSize: FontSize.lg,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  form: {
    gap: Spacing.two,
  },
  label: {
    textAlign: "right",
    fontSize: FontSize.xs,
    fontFamily: FontFamily.semiBold,
    color: C.textDark,
    opacity: 0.8,
  },
  input: {
    height: 44,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    paddingHorizontal: Spacing.two + 2,
    textAlign: "right",
    fontSize: FontSize.md,
    color: C.textDark,
    backgroundColor: C.lightBg,
  },
  rowInputs: {
    flexDirection: "row-reverse",
  },
  formDivider: {
    height: 1,
    backgroundColor: C.border,
    marginVertical: Spacing.two,
  },
  // ─── Payment selector ─────────────────────────────────────────────────────
  paymentSelector: {
    flexDirection: "row-reverse",
    gap: Spacing.two,
    marginVertical: Spacing.one,
  },
  payMethodBtn: {
    flex: 1,
    height: 44,
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: 10,
    backgroundColor: C.white,
    justifyContent: "center",
    alignItems: "center",
  },
  payMethodActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryLight,
  },
  payText: {
    fontSize: FontSize.md,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  payActiveText: {
    color: C.primary,
  },
  manualPayCard: {
    padding: Spacing.three,
    borderRadius: 12,
    backgroundColor: C.bgElement,
    gap: Spacing.one,
    marginTop: Spacing.one,
  },
  manualPayInstruction: {
    fontSize: FontSize.xs,
    color: C.textMuted,
    textAlign: "right",
    lineHeight: 16,
  },
  accountRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: Spacing.two,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.border,
    padding: Spacing.two,
    borderRadius: 8,
  },
  copyBtn: {
    backgroundColor: C.primaryLight,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.one,
    borderRadius: 6,
  },
  copyBtnText: {
    color: C.primary,
    fontFamily: FontFamily.bold,
    fontSize: FontSize.xs,
  },
  accountNumber: {
    fontFamily: FontFamily.bold,
    fontSize: FontSize.base,
    color: C.textDark,
    letterSpacing: 0.5,
  },
  submitOrderBtn: {
    backgroundColor: C.primary,
    paddingVertical: Spacing.three,
    borderRadius: 12,
    alignItems: "center",
    marginTop: Spacing.three,
  },
  submitOrderText: {
    color: C.white,
    fontSize: FontSize.base,
    fontFamily: FontFamily.bold,
  },
});
