import { StyleSheet } from "react-native";
import { AppColors, FontFamily, FontSize, Spacing, MaxContentWidth } from "@/constants/theme";

const C = AppColors;

export const cartStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F3F4F6",
    paddingTop: Spacing.two,
  },
  centered: {
    justifyContent: "center",
    alignItems: "center",
  },
  safeArea: {
    flex: 1,
    maxWidth: MaxContentWidth,
    width: "100%",
    alignSelf: "center",
  },
  headerContainer: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0, 0, 0, 0.05)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 2,
    backgroundColor: C.white,
    zIndex: 10,
  },
  headerTop: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Spacing.four,
    paddingBottom: 10,
    paddingTop: 6,
  },
  headerRightSide: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
  },
  headerLogo: {
    width: 32,
    height: 32,
  },
  headerTextGroup: {
    alignItems: "flex-end",
    justifyContent: "center",
  },
  appName: {
    fontSize: FontSize.xl,
    fontFamily: FontFamily.bold,
    color: C.primary,
    lineHeight: 22,
  },
  appSubtitle: {
    fontSize: 9,
    fontFamily: FontFamily.medium,
    color: C.textMuted,
    lineHeight: 12,
  },
  headerLeftSide: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 10,
  },
  headerSearchIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: C.bgElement,
    justifyContent: "center",
    alignItems: "center",
  },
  userAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: C.primary,
  },
  mainContent: {
    flex: 1,
    maxWidth: MaxContentWidth,
    width: "100%",
    alignSelf: "center",
  },
  cartTitleSection: {
    paddingHorizontal: Spacing.four,
    paddingTop: Spacing.three,
    paddingBottom: Spacing.two,
    alignItems: "flex-end",
  },
  cartTitleText: {
    fontSize: 22,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  cartSubtitleText: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.medium,
    color: C.textMuted,
    marginTop: 2,
  },
  scrollContent: {
    paddingBottom: 110,
  },
  listContainer: {
    gap: Spacing.two,
    paddingHorizontal: Spacing.four,
  },
  // ─── Cart Item Card ────────────────────────────────────────────────────────
  cartItemCard: {
    flexDirection: "row-reverse",
    borderRadius: 16,
    padding: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.white,
    position: "relative",
  },
  cartItemImage: {
    width: 80,
    height: 80,
    borderRadius: 12,
  },
  cartItemDetails: {
    flex: 1,
    marginRight: 12,
    marginLeft: 95, // Safe gap to avoid overlap with left controls
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 4,
  },
  cartItemName: {
    fontSize: FontSize.lg,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  cartItemCat: {
    fontSize: FontSize.xs,
    color: C.textMuted,
  },
  cartItemPrice: {
    color: C.textDark,
    fontSize: FontSize.base,
    fontFamily: FontFamily.bold,
  },
  itemQuantityContainer: {
    position: "absolute",
    bottom: 12,
    left: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.bgElement,
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: C.border,
    gap: 4,
    height: 30,
  },
  actionBtn: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: C.white,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 1,
  },
  quantityText: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.bold,
    color: C.textDark,
    marginHorizontal: 6,
  },
  deleteBtn: {
    position: "absolute",
    top: 12,
    left: 12,
    padding: 4,
  },
  // ─── Summary card ─────────────────────────────────────────────────────────
  summaryCard: {
    marginHorizontal: Spacing.four,
    marginTop: Spacing.four,
    borderRadius: 16,
    padding: Spacing.three + 2,
    gap: Spacing.two,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.white,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  summaryTitle: {
    textAlign: "right",
    fontSize: FontSize.lg,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  summaryRow: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
  },
  summaryLabel: {
    fontSize: FontSize.md,
    color: C.textMuted,
  },
  summaryValue: {
    fontSize: FontSize.md,
    fontFamily: FontFamily.semiBold,
    color: C.textDark,
  },
  freeDelivery: {
    fontSize: FontSize.md,
    fontFamily: FontFamily.bold,
    color: C.success,
  },
  divider: {
    height: 1,
    backgroundColor: C.border,
    marginVertical: Spacing.one,
  },
  totalLabel: {
    fontSize: FontSize.lg,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  totalValue: {
    fontSize: FontSize.xl,
    fontFamily: FontFamily.bold,
    color: C.primary,
  },
  checkoutBtn: {
    backgroundColor: C.primary,
    paddingVertical: Spacing.three,
    borderRadius: 12,
    alignItems: "center",
    marginTop: Spacing.two,
  },
  checkoutBtnText: {
    color: C.white,
    fontSize: FontSize.md,
    fontFamily: FontFamily.bold,
  },
  // ─── Empty state ──────────────────────────────────────────────────────────
  emptyTitle: {
    fontSize: FontSize.xxl,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  emptySubtitle: {
    textAlign: "center",
    marginBottom: Spacing.four,
    color: C.textMuted,
  },
  shopBtn: {
    backgroundColor: C.primary,
    paddingHorizontal: Spacing.four,
    paddingVertical: Spacing.two,
    borderRadius: 12,
  },
  shopBtnText: {
    color: C.white,
    fontFamily: FontFamily.bold,
  },
  // ─── Checkout view ────────────────────────────────────────────────────────
  checkoutContainer: {
    marginHorizontal: Spacing.four,
    borderRadius: 16,
    padding: Spacing.three + 2,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.white,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  checkoutHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.three,
  },
  backBtn: {
    paddingVertical: Spacing.one,
  },
  backBtnText: {
    color: C.primary,
    fontSize: FontSize.sm,
    fontFamily: FontFamily.bold,
  },
  checkoutTitle: {
    fontSize: FontSize.lg,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  form: {
    gap: Spacing.two,
  },
  label: {
    textAlign: "right",
    fontSize: FontSize.xs,
    fontFamily: FontFamily.semiBold,
    color: C.textDark,
    opacity: 0.8,
  },
  input: {
    height: 44,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    paddingHorizontal: Spacing.two + 2,
    textAlign: "right",
    fontSize: FontSize.md,
    color: C.textDark,
    backgroundColor: C.lightBg,
  },
  rowInputs: {
    flexDirection: "row-reverse",
  },
  formDivider: {
    height: 1,
    backgroundColor: C.border,
    marginVertical: Spacing.two,
  },
  // ─── Payment selector ─────────────────────────────────────────────────────
  paymentSelector: {
    flexDirection: "row-reverse",
    gap: Spacing.two,
    marginVertical: Spacing.one,
  },
  payMethodBtn: {
    flex: 1,
    height: 44,
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: 10,
    backgroundColor: C.white,
    justifyContent: "center",
    alignItems: "center",
  },
  payMethodActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryLight,
  },
  payText: {
    fontSize: FontSize.md,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  payActiveText: {
    color: C.primary,
  },
  manualPayCard: {
    padding: Spacing.three,
    borderRadius: 12,
    backgroundColor: C.bgElement,
    gap: Spacing.one,
    marginTop: Spacing.one,
  },
  manualPayInstruction: {
    fontSize: FontSize.xs,
    color: C.textMuted,
    textAlign: "right",
    lineHeight: 16,
  },
  accountRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: Spacing.two,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.border,
    padding: Spacing.two,
    borderRadius: 8,
  },
  copyBtn: {
    backgroundColor: C.primaryLight,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.one,
    borderRadius: 6,
  },
  copyBtnText: {
    color: C.primary,
    fontFamily: FontFamily.bold,
    fontSize: FontSize.xs,
  },
  accountNumber: {
    fontFamily: FontFamily.bold,
    fontSize: FontSize.base,
    color: C.textDark,
    letterSpacing: 0.5,
  },
  submitOrderBtn: {
    backgroundColor: C.primary,
    paddingVertical: Spacing.three,
    borderRadius: 12,
    alignItems: "center",
    marginTop: Spacing.three,
  },
  submitOrderText: {
    color: C.white,
    fontSize: FontSize.base,
    fontFamily: FontFamily.bold,
  },
  // ─── Map picker inputs ──────────────────────────────────────────────────
  addressInputRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: Spacing.two,
  },
  addressInput: {
    flex: 1,
  },
  mapPickerBtn: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: C.primaryLight,
    borderWidth: 1,
    borderColor: C.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  // ─── Map Modal Styles ──────────────────────────────────────────────────────
  modalContainer: {
    flex: 1,
    backgroundColor: C.white,
  },
  modalHeader: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Spacing.four,
    paddingVertical: Spacing.three,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  modalTitle: {
    fontSize: FontSize.lg,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  closeBtn: {
    padding: Spacing.one,
  },
  mapWrapper: {
    flex: 1,
    position: "relative",
  },
  mapView: {
    flex: 1,
  },
  markerFixed: {
    position: "absolute",
    left: "50%",
    top: "50%",
    marginLeft: -20,
    marginTop: -40,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 5,
  },
  mapOverlayCard: {
    position: "absolute",
    bottom: Spacing.four,
    left: Spacing.four,
    right: Spacing.four,
    backgroundColor: C.white,
    borderRadius: 16,
    padding: Spacing.three,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    gap: Spacing.two,
  },
  mapOverlayTitle: {
    fontSize: FontSize.xs,
    color: C.textMuted,
    fontFamily: FontFamily.medium,
    textAlign: "right",
  },
  mapOverlayAddress: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.semiBold,
    color: C.textDark,
    textAlign: "right",
  },
  mapConfirmBtn: {
    backgroundColor: C.primary,
    paddingVertical: Spacing.two + 2,
    borderRadius: 10,
    alignItems: "center",
  },
  mapConfirmText: {
    color: C.white,
    fontFamily: FontFamily.bold,
    fontSize: FontSize.md,
  },
  gpsBtn: {
    position: "absolute",
    bottom: 160,
    right: Spacing.four,
    backgroundColor: C.white,
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 10,
  },
  // ─── Location display styles ──────────────────────────────────────────────
  locationDetailsCard: {
    backgroundColor: C.bgElement,
    borderRadius: 12,
    padding: Spacing.three,
    borderWidth: 1,
    borderColor: C.border,
    marginTop: Spacing.one,
  },
  locationDetailsHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    paddingBottom: Spacing.two,
    marginBottom: Spacing.two,
  },
  locationDetailsTitle: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  emptyLocationWarningGradient: {
    borderRadius: 12,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#FCA5A5",
    overflow: "hidden",
    marginTop: Spacing.one,
  },
  emptyLocationWarningContent: {
    alignItems: "center",
    padding: Spacing.four,
    gap: Spacing.two,
  },
  emptyLocationText: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.medium,
    color: "#991B1B",
    textAlign: "center",
    lineHeight: 20,
  },
  goToProfileBtn: {
    backgroundColor: C.primary,
    paddingHorizontal: Spacing.four,
    paddingVertical: Spacing.two,
    borderRadius: 20,
    shadowColor: C.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
    marginTop: Spacing.one,
  },
  goToProfileBtnText: {
    color: C.white,
    fontFamily: FontFamily.bold,
    fontSize: FontSize.xs,
  },
  locationInfoBody: {
    gap: Spacing.one,
  },
  locationInfoRow: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  locationValueText: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.semiBold,
    color: C.textDark,
    flex: 1,
    textAlign: "left",
    marginRight: Spacing.two,
  },
  locationLabelText: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.medium,
    color: C.textMuted,
  },
  locationHintBox: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 6,
    backgroundColor: C.white,
    padding: Spacing.two,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    marginTop: Spacing.two,
  },
  locationHintText: {
    fontSize: 9,
    fontFamily: FontFamily.medium,
    color: C.textMuted,
    flex: 1,
    textAlign: "right",
  },
});
