import { StyleSheet, Dimensions } from "react-native";
import { AppColors, FontFamily, FontSize, Spacing } from "@/constants/theme";

const { width } = Dimensions.get("window");
export const cardWidth = 230;

const C = AppColors;

export const indexStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.lightBg,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: C.lightBg,
  },
  // ─── Absolute translucent header ───────────────────────────────────────────
  headerContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    backgroundColor: "#FFEBEB",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0, 0, 0, 0.05)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 3,
  },
  headerSafeArea: {
    paddingBottom: Spacing.four,
  },
  headerTop: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Spacing.four,
    marginTop: 12,
  },
  appName: {
    fontSize: FontSize.xl,
    fontFamily: FontFamily.bold,
    color: C.primary,
  },
  welcomeUserRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  userGreet: {
    fontSize: FontSize.sm,
    color: C.textMuted,
    fontFamily: FontFamily.medium,
  },
  // ─── Search bar ────────────────────────────────────────────────────────────
  searchBarContainer: {
    flexDirection: "row-reverse",
    alignItems: "center",
    backgroundColor: C.white,
    marginHorizontal: Spacing.four,
    marginTop: Spacing.two,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: Spacing.three,
    height: 40,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 4,
    elevation: 1,
  },
  searchIcon: {
    marginLeft: Spacing.two,
  },
  searchInput: {
    flex: 1,
    fontFamily: FontFamily.medium,
    fontSize: FontSize.md,
    textAlign: "right",
    color: C.textDark,
  },
  // ─── Category chips ────────────────────────────────────────────────────────
  categoriesScroll: {
    flexDirection: "row-reverse",
    paddingHorizontal: Spacing.four,
    marginTop: Spacing.two + 2,
    gap: Spacing.two,
  },
  categoryChip: {
    paddingHorizontal: Spacing.three + 2,
    paddingVertical: Spacing.one + 2,
    borderRadius: 20,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.border,
  },
  categoryChipSelected: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  categoryText: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.semiBold,
    color: C.textDark,
  },
  categoryTextSelected: {
    color: C.white,
  },
  // ─── Product grid ─────────────────────────────────────────────────────────
  scrollList: {
    paddingTop: 216,
    paddingBottom: 110,
  },
  columnWrapper: {
    justifyContent: "space-between",
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  cardContainer: {
    width: cardWidth,
    height: 300,
    backgroundColor: C.white,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.015,
    shadowRadius: 6,
    elevation: 1,
  },
  imageWrapper: {
    width: "100%",
    height: 150,
    backgroundColor: C.bgElement,
    position: "relative",
  },
  productImage: {
    width: "100%",
    height: "100%",
  },
  categoryBadge: {
    position: "absolute",
    bottom: 6,
    left: 6,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 8,
    paddingHorizontal: Spacing.two,
    paddingVertical: 2,
  },
  categoryBadgeText: {
    fontSize: FontSize.xxs,
    fontFamily: FontFamily.bold,
    color: C.primary,
  },
  cardActionFloating: {
    position: "absolute",
    top: 6,
    right: 6,
    zIndex: 5,
  },
  cardInfo: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 14,
    flex: 1,
    justifyContent: "space-between",
  },
  productName: {
    fontSize: FontSize.base,
    fontFamily: FontFamily.bold,
    color: C.textDark,
    textAlign: "right",
  },
  priceRow: {
    flexDirection: "row-reverse",
    justifyContent: "flex-start",
    marginTop: 2,
  },
  productPrice: {
    fontSize: FontSize.lg,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  currencyText: {
    fontSize: FontSize.xxs,
    color: C.primary,
    fontFamily: FontFamily.bold,
  },
  addToCartCircularBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.primary,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: C.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  quantitySelector: {
    flexDirection: "row-reverse",
    alignItems: "center",
    backgroundColor: C.bgElement,
    borderRadius: 16,
    paddingHorizontal: 6,
    paddingVertical: 3,
    gap: 8,
  },
  circleBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: C.white,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  quantityLabel: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.bold,
    color: C.textDark,
  },
  emptyListContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
    gap: Spacing.two,
  },
  emptyListText: {
    color: C.textMuted,
    fontSize: FontSize.md,
    textAlign: "center",
  },
  // ─── Login screen ─────────────────────────────────────────────────────────
  loginContainer: {
    flex: 1,
    backgroundColor: C.white,
  },
  loginSafeArea: {
    flex: 1,
  },
  loginContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: Spacing.five,
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: Spacing.six,
  },
  logoImage: {
    width: 90,
    height: 90,
    marginBottom: Spacing.two,
  },
  brandTitle: {
    fontSize: FontSize.h1,
    fontFamily: FontFamily.bold,
    color: C.primary,
  },
  brandSubtitle: {
    fontSize: FontSize.md,
    color: C.textMuted,
    fontFamily: FontFamily.medium,
    marginTop: 2,
  },
  loginFormCard: {
    width: "100%",
    backgroundColor: C.lightBg,
    borderRadius: 20,
    padding: Spacing.four,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.03,
    shadowRadius: 12,
    elevation: 3,
  },
  welcomeText: {
    fontSize: FontSize.xl,
    fontFamily: FontFamily.bold,
    color: C.textDark,
    textAlign: "center",
    marginBottom: Spacing.two,
  },
  welcomeDesc: {
    fontSize: FontSize.md,
    color: C.textMuted,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: Spacing.five,
  },
  googleLoginBtn: {
    flexDirection: "row-reverse",
    backgroundColor: C.primary,
    width: "100%",
    height: 48,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: C.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  googleLoginBtnText: {
    color: C.white,
    fontSize: FontSize.base,
    fontFamily: FontFamily.bold,
  },
  sectionContainer: {
    marginBottom: Spacing.four,
  },
  sectionHeader: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Spacing.four,
    marginBottom: Spacing.two,
  },
  sectionTitle: {
    fontSize: FontSize.lg,
    fontFamily: FontFamily.bold,
    color: C.textDark,
    textAlign: "right",
  },
  horizontalList: {
    paddingHorizontal: Spacing.four,
    paddingBottom: Spacing.two,
  },
  headerTitleRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  totalCountBadge: {
    backgroundColor: C.primary + "15",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    marginRight: 8,
  },
  totalCountText: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.bold,
    color: C.primary,
  },
  sectionCount: {
    fontSize: FontSize.base,
    fontFamily: FontFamily.medium,
    color: C.textMuted,
  },
  cardMetaRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
    marginTop: 2,
  },
  cardMetaItem: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 2,
  },
  cardMetaText: {
    fontSize: FontSize.xxs,
    fontFamily: FontFamily.medium,
    color: C.textMuted,
  },
  productDescSnippet: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.regular,
    color: C.textMuted,
    textAlign: "right",
    lineHeight: 16,
    marginTop: 4,
  },
  cardActionRow: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  inlineAddToCartBtn: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primary,
    paddingHorizontal: 12,
    borderRadius: 8,
    height: 30,
  },
  inlineAddToCartText: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.bold,
    color: C.white,
  },
  inlineQuantitySelector: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryLight,
    borderWidth: 1,
    borderColor: C.primary,
    borderRadius: 8,
    paddingHorizontal: 6,
    height: 30,
  },
  inlineActionBtn: {
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  inlineQuantityLabel: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.bold,
    color: C.primary,
    minWidth: 16,
    textAlign: "center",
    marginHorizontal: 4,
  },
});
